export const IMG_CDN_URL =
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/";

export const FETCH_MENU_URL =
  "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=19.0751377&lng=72.9091436&restaurantId=";

export const FETCH_LIST_URL =
  "https://www.swiggy.com/dapi/restaurants/list/v5?lat=19.0751377&lng=72.9091436&is-seo-homepage-enabled=true&page_type=DESKTOP_WEB_LISTING";
// default driven UI
export const RestaurantList = [
  {
    info: {
      id: "28283",
      name: "Chinese Wok",
      cloudinaryImageId: "e0839ff574213e6f35b3899ebf1fc597",
      locality: "Chembur",
      areaName: "Chembur",
      costForTwo: "₹250 for two",
      cuisines: ["Chinese", "Asian", "Tibetan", "Desserts"],
      avgRating: 4.3,
      parentId: "61955",
      avgRatingString: "4.3",
      totalRatingsString: "10K+",
    },
  },
  {
    info: {
      id: "19972",
      name: "Burger King",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/11/7f76a072-c1bc-4d74-ac56-33e0eea20c1e_19972.JPG",
      locality: "Rcity",
      areaName: "Ghatkopar West",
      costForTwo: "₹350 for two",
      cuisines: ["Burgers", "American"],
      avgRating: 4.1,
      parentId: "166",
      avgRatingString: "4.1",
      totalRatingsString: "10K+",
    },
  },
  {
    info: {
      id: "41969",
      name: "Pizza Hut",
      cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
      locality: "Ghatkopar West",
      areaName: "Ghatkopar West",
      costForTwo: "₹300 for two",
      cuisines: ["Pizzas"],
      avgRating: 3.7,
      parentId: "721",
      avgRatingString: "3.7",
      totalRatingsString: "5K+",
    },
  },
  {
    info: {
      id: "764056",
      name: "Theobroma",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/7/22/066bc226-7e34-4e5b-b64f-c052a66e18c2_764056.jpg",
      locality: "Laxmi Palace",
      areaName: "Ghatkopar",
      costForTwo: "₹400 for two",
      cuisines: ["Bakery", "Desserts"],
      avgRating: 4.7,
      veg: true,
      parentId: "1040",
      avgRatingString: "4.7",
      totalRatingsString: "500+",
    },
  },
  {
    info: {
      id: "16049",
      name: "KFC",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/17/283329f9-5ad8-4c46-9177-6b23b6eb2966_16049.JPG",
      locality: "Chembur",
      areaName: "Chembur",
      costForTwo: "₹400 for two",
      cuisines: ["Burgers", "Fast Food", "Rolls & Wraps"],
      avgRating: 4.2,
      parentId: "547",
      avgRatingString: "4.2",
      totalRatingsString: "10K+",
    },
  },
  {
    info: {
      id: "23758",
      name: "McDonald's",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/1/b5c7e325-a2b3-4334-b104-0b20df81dd93_23758.JPG",
      locality: "M G Road",
      areaName: "Kurla",
      costForTwo: "₹400 for two",
      cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
      avgRating: 4.4,
      parentId: "630",
      avgRatingString: "4.4",
      totalRatingsString: "10K+",
    },
  },
  {
    info: {
      id: "24511",
      name: "Domino's Pizza",
      cloudinaryImageId: "d0450ce1a6ba19ea60cd724471ed54a8",
      locality: "R-City, Ghatkopar(West)",
      areaName: "Ghatkopar East",
      costForTwo: "₹400 for two",
      cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
      avgRating: 4,
      parentId: "2456",
      avgRatingString: "4.0",
      totalRatingsString: "5K+",
    },
  },
  {
    info: {
      id: "46877",
      name: "Wow! Momo",
      cloudinaryImageId: "64fd45fd9f44c1737bc446e470bed666",
      locality: "Ghatkopar West",
      areaName: "Ghatkopar West",
      costForTwo: "₹300 for two",
      cuisines: [
        "Tibetan",
        "Healthy Food",
        "Asian",
        "Chinese",
        "Snacks",
        "Continental",
        "Desserts",
        "Beverages",
      ],
      avgRating: 4.4,
      parentId: "1776",
      avgRatingString: "4.4",
      totalRatingsString: "1K+",
    },
  },
  {
    info: {
      id: "33561",
      name: "Juno's Pizza - Baking Fresh Since 1974",
      cloudinaryImageId: "a855f6657b55a1f2c3a7aac9101199bc",
      locality: "JAYANT VILLA",
      areaName: "Ghatkopar East",
      costForTwo: "₹1000 for two",
      cuisines: ["Pizzas", "Pastas", "Jain", "Italian", "Fast Food"],
      avgRating: 4.2,
      parentId: "512339",
      avgRatingString: "4.2",
      totalRatingsString: "1K+",
    },
  },
  {
    info: {
      id: "387322",
      name: "La Pino'z Pizza",
      cloudinaryImageId: "pf3fw4qzazsu0dqngrry",
      locality: "Ghatkopar East",
      areaName: "Ghatkopar Vikhroli",
      costForTwo: "₹300 for two",
      cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
      avgRating: 4.2,
      parentId: "4961",
      avgRatingString: "4.2",
      totalRatingsString: "1K+",
    },
  },
  {
    info: {
      id: "395479",
      name: "Chaayos Chai+Snacks=Relax",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/17/dfbcecfc-b380-4648-930a-b9b56b21e781_395479.JPG",
      locality: "K - Star Mall DK Chembur",
      areaName: "Ghatkopar Vikhroli",
      costForTwo: "₹250 for two",
      cuisines: [
        "Bakery",
        "Beverages",
        "Chaat",
        "Desserts",
        "Home Food",
        "Italian",
        "Maharashtrian",
        "Snacks",
        "Street Food",
        "Sweets",
      ],
      avgRating: 4.6,
      parentId: "281782",
      avgRatingString: "4.6",
      totalRatingsString: "1K+",
    },
  },
  {
    info: {
      id: "646672",
      name: "Bakingo-Cakes & Desserts",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/8/5/c43f09e2-37ab-4559-ba21-e16a4e7cfb04_646672.JPG",
      locality: "Chembur",
      areaName: "Anwar Compound",
      costForTwo: "₹300 for two",
      cuisines: ["Bakery", "Desserts", "Beverages", "Snacks"],
      avgRating: 4.5,
      parentId: "3818",
      avgRatingString: "4.5",
      totalRatingsString: "1K+",
    },
  },
  {
    info: {
      id: "649531",
      name: "Kwality Walls Frozen Dessert and Ice Cream Shop",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/13/b62d0931-507e-4965-a060-724005f37f2e_649531.JPG",
      locality: "Tilak road",
      areaName: "Ghatkopar Vikhroli",
      costForTwo: "₹200 for two",
      cuisines: ["Desserts", "Ice Cream", "Ice Cream Cakes"],
      avgRating: 4.6,
      veg: true,
      parentId: "582",
      avgRatingString: "4.6",
      totalRatingsString: "100+",
    },
  },
  {
    info: {
      id: "87705",
      name: "NIC Ice Creams",
      cloudinaryImageId: "18d8b8fb6bac8063a6fa886e20148110",
      locality: "Vikash Apartment",
      areaName: "Ghatkopar",
      costForTwo: "₹120 for two",
      cuisines: ["Ice Cream", "Desserts"],
      avgRating: 4.6,
      veg: true,
      parentId: "6249",
      avgRatingString: "4.6",
      totalRatingsString: "10K+",
    },
  },
];
